---

- hosts: all
  become: true
  strategy: free

  vars_files:
    - ./secrets.yaml

  tasks:
  #- debug: var=ansible_local.insights.system_id

  - name: Remove this system from Insights
    ansible.builtin.command: insights-client --unregister
    when: ansible_local.insights.system_id is defined

  - name: Unsubscribe the system from Red Hat RHSM
    ansible.builtin.command: subscription-manager unregister
    # This approach isn't currently working on rhel9
    #redhat_subscription:
      #state: absent
