---

- hosts: leapp
  become: yes

  tasks:

    - name: Enable the appropriate RHEL extras repository
      rhsm_repository:
        name: rhel-{{ ansible_distribution_major_version }}-server-extras-rpms
        state: enabled
      when: (ansible_distribution_major_version == "6") or
            (ansible_distribution_major_version == "7")

    - name: make sure leapp is present
      yum:
        name: leapp
        state: present
