= Demo Convert2RHEL

We recommend you review the latest Convert2RHEL documentation before proceeding.
 - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index[Converting from an RPM-based Linux distribution to RHEL]


*NOTE* You will need to provide some login credentials so that Convert2RHEL can 
to pull packages from Red Hat's CDN service.  The supplied ansible playbook will automate the registration providing you've got a valid secrets.yaml.
A sample link:../ansible/secrets.yaml.example[secrets.yaml.example] has been provided which you'll need to update with a username
and password.

[source,bash]
----
cd ansible
cp secrets.yaml.example secrets.yaml
nano secrets.yaml

# Update the secrets file

cd -
----


*NOTE* If you're using the standard Centos 8 Cloud Image from the previous step this will need to be patched to Centos 8.5
before running Convert2RHEL.

[source,bash]
----
ssh leapp2rhel
sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

yum -y upgrade

# Confirm we're running version 8.5
cat /etc/centos-release

logout
----

We're going to use an ansible playbook from the upstream project team to install
the core requirements for convert2rhel to run

[source,bash]
----
cd ansible

curl -L -O https://github.com/oamg/convert2rhel/raw/main/ansible/setup-convert2rhel.yml

ansible-playbook  -i hosts setup-convert2rhel.yml 
----


For the run portion we need to make sure we've got a valid Red Hat portal login in our secrets.yaml.

The actual run can take over 10 minutes depending on your connection and VM performance, and once completed 
the VM will be rebooted.

[source,bash]
----
curl -L -O https://github.com/oamg/convert2rhel/raw/main/ansible/run-convert2rhel.yml

ansible-playbook  -i hosts run-convert2rhel.yml --extra-vars "@secrets.yaml"

----

If you want to watch some of the update progress you can remote into the virtual machine and monitor the yum log

[source,bash]
----
ssh leapp2rhel

tail -f /var/log/yum.log

----

---
link:Demo_Leapp.adoc[Next Step] or
link:../README.adoc[Return]
