= Deployment of Cloud / Virt ready OS Images

If you're running this demo code on a cloud hosted environment then simply select their pre-configured
cloud ready image, and skip to the setup of the demo tooling using link:./Demo_Setup.adoc[Ansible].

Follow these instructions to run a local VM under KVM + Libvirt.

== Validated Images ==

Centos

* https://cloud.centos.org/altarch/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2[CentOS-7-x86_64-GenericCloud-2009.qcow2]
* https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2[CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2] - Convert2RHEL only

Red Hat Enterprise Linux

* rhel-server-7.9-x86_64-kvm.qcow2

The process I'm using is I create a working snapshot off the working image and then 
customize the image to set a simple password for the root user. Ideally we should be using
the cloud-init capabilities to inject a valid user and credentials, but this is a quick
hack to speed up this demo deployment.

== Deployment Customisation

We provide a sample local environment file link:../local.env.sample[local.env.sample].
You need to copy this to **local.env**  and update the following varibles to suit you local KVM environment

- MY_USER to your usename so that you ssh pubkey can be utilised
- BASE_DIR to the location you use to store your base cloud qcow2 images
- VM_DIR to your working directory for running KVM instances
- VM_BRIDGE to match the network you're using

The current process uses ``virt-customize`` to strip out cloud-init
from the base image and set an initial password for the root user to
_password_.

== Scriptied deployment of Centos / RHEL VM under KVM 

We now have a link:../deploy_vm.sh[fully scripted] approach once you've specified the required overrides in your **local.env** file.

[source,bash]
----
# For Centos 7
sudo  ./deploy_vm.sh create centos7

# For Centos 8
sudo  ./deploy_vm.sh create centos8

# For RHEL 8
sudo  ./deploy_vm.sh create rhel7

# For RHEL 8
sudo  ./deploy_vm.sh create rhel8

----

== Manual Deployment Approach ==
[source,bash]
----
# Replace these with the locations you use to store base images
# and running VM Images
BASE_DIR=/opt/Virtual/ISO
VM_DIR=/opt/Virtual/images

# Username you're using for general management so we can add SSH Keys
MY_USER=sellis

# For Centos 7
OS_VARIANT=centos7
BASE_IMAGE=CentOS-7-x86_64-GenericCloud-2009.qcow2

# For Centos 8
OS_VARIANT=centos8
BASE_IMAGE=CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2

# For RHEL 7.9
OS_VARIANT=rhel7.9
BASE_IMAGE=rhel-server-7.9-x86_64-kvm.qcow2

# For RHEL 8.5
OS_VARIANT=rhel8.5
BASE_IMAGE=rhel-8.5-x86_64-kvm.qcow2

# Define our virtual environment
# Make sure the VM_BRIDE matches a bridge or nat network in your
# libvirt environment

VM_NAME=LEAPP2RHEL
VM_MEMORY=2048
VM_CPU=2
VM_BRIDGE=virbr1

VM_BASE=${BASE_DIR}/${BASE_IMAGE}
VM_IMAGE=${VM_DIR}/Leepp2RHEL.qcow2

# Create our working snapshot
qemu-img create -f qcow2 -F qcow2 \
-o backing_file=${VM_BASE} ${VM_IMAGE}

# If we're going to add an SSH Key we need to re-label due to SELinux
ADD_SSH_KEY=

[ -f /home/${MY_USER}/.ssh/id_rsa.pub ] && \
  ADD_SSH_KEY="--ssh-inject root:file:/home/${MY_USER}/.ssh/id_rsa.pub --selinux-relabel"

# Enable root password login and remove cloud-init
# Add our user ssh pubkey if available

virt-customize -a ${VM_IMAGE} \
 --root-password password:password --uninstall cloud-init \
 ${ADD_SSH_KEY} \
 --run-command 'echo PermitRootLogin yes >> /etc/ssh/sshd_config'

# Then Create the VM

virt-install --name ${VM_NAME} --memory ${VM_MEMORY} --vcpus ${VM_CPU} \
    --disk path=$VM_IMAGE,format=qcow2,bus=scsi,discard=unmap \
    --os-variant=${OS_VARIANT} \
    --controller=type=scsi,model=virtio-scsi \
    --connect qemu:///system \
    --virt-type kvm \
    --noautoconsole \
    --import \
    --network type=bridge,source=${VM_BRIDGE} --graphics vnc

virsh console ${VM_NAME}

----

== Post deployment steps

The Cloud Ready Centos 7 & 8 images currently allow ssh login as root. 
If you're working with a vanilla cloud image on AWS or Azure you might
need to type the following via a remote console.

[source,bash]
----
echo "PermitRootLogin yes" > /etc/ssh/sshd_config.d/01-permitrootlogin.conf
systemctl restart sshd
----

I also recommend adding an entry in ~/.ssh/config with the correct IP address for your VM
which will simplify running the ansible playbook. If you're using KVM you might see the
IP address in the virsh console.

Another option is to query arp and look for new addresses on your bridge device

[source,bash]
----
arp -n | grep ${VM_BRIDGE}
----

Or you can use the virtual console to login as the root user and confirm the hosts IP Address

----
Host leapp2rhel
Hostname 192.168.124.138
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
User root
----

You should then enable login via your ssh-key so that Ansible can automate the rest of the setup

[source,bash]
----
ssh-copy-id leapp2rhel
----

== Environment Cleanup

You can now use the link:../deploy_vm.sh[deployment script] to clean up your environment

[source,bash]
----
sudo ./deploy_vm.sh cleanup
----

Alternatively if you've used the manual deployment approayc, and providing you've got the same shell open,
you can quickly clean up the deployed environment via

[source,bash]
----
virsh destroy ${VM_NAME}
virsh undefine ${VM_NAME}
rm ${VM_IMAGE} 
----

---
link:Demo_Convert2RHEL.adoc[Convert OS Image to RHEL] or
link:Demo_Leapp.adoc[Upgrade to the next release of RHEL] or
link:../README.adoc[Return]
