= Demo Red Hat Insights

https://console.redhat.com/insights/[Red Hat Insights] provides pro-active analysis and reporting
of potential security issues and sytem performance tuning

This is a key value-add for the Red Hat Enterprise Linux platform.

This demo requires that the base OS as been convereted to RHEL 7.9 or newer

== Demo Pre-work ==

First we need to have deployed and converted a Centos VM to RHEL

- Deploy a link:Demo_VM.adoc[local or cloud hosted Centos Linux environment]
- Convert link:./Demo_Convert2RHEL.adoc[Centos environment to RHEL] with Convert2RHEL


=== Automated Deployment ===

Here we use the Ansible
https://github.com/RedHatInsights/insights-client-role[insights-client-role]
to enable the service

[source,bash]
----

cd ansible

ansible-galaxy  install -r requirements.yaml

ansible-playbook -i hosts setup_insights.yaml 

----

=== Manual environment configuration ===

TBC

== Live Demo ==

The flow is

* Enable the sytem via Insights
* Login to https://console.redhat.com/insights/[Red Hat Insights]
* Tag your new systems as the group LEAPP2RHEL
* Filter on tag LEAPP2RHEL

== Sample Security issues

=== Outstanding RHEL 8.4 issues ===

The upgrade from RHEL 7.9 is currently to version 8.4 which has a number of known issues.

You can show these outstanding issues via the insights dashboard, including an important CVE.

=== PwnKit - policykit issue ===

To install the comprise on a RHEL7 host

[source,bash]
----
yum downgrade polkit-0.112-11.el7_3.x86_64

insights-client
----

For RHEL8 we need to make sure we can access older RPMs as the upgrade
version locks the environment until we complete the cleanup tasks.

[source,bash]
----

subscription-manager release --unset
yum check-update

yum downgrade polkit-0.115-9.el8.x86_64

insights-client
----

You can then view the issue via the
https://console.redhat.com/insights/[Red Hat Insights] dashboard,
and confirm the issue is in place via the exploit Live Demo part of
the

- link:./Demo_PwnKit.adoc[PwnKit security escallation and remediation]

You can then remediate the issue with an update, or via the Ansible
remediation capabilities in Insights.

link:../README.adoc[Return]
