= Demo of RHEL 8.x and 9 for APAC Webinar

Deployment steps for setting up an environment to showcase


* Cockpit console
* leapp from RHEL8 -> RHEL9
* https://www.redhat.com/en/technologies/management/insights[Red Hat Insights]
* Cloud hosted Image Builder
* AWS deployment of Cloud Image

This leverages the following parts of our core demo environment

- Deploy a link:./Demo_VM.adoc[local or cloud hosted Centos Linux environment]
- Upgrade link:./Demo_Leapp.adoc[your RHEL environment] via Leapp

== Environment deployment

This is the pre-work to setup the initial environment and assumes you've completed
any of the pre-steps under the links above

[source,bash]
----
sudo VM_NAME=RHEL8x ./deploy_vm.sh create rhel8

sudo VM_NAME=RHEL9 ./deploy_vm.sh create rhel9
----

Add these hosts into your local ~/.ssh/config for and confirm you have SSH access.
In addition you'll require a hosts.demo file for ansible with the following entries

----
[all]
rhel8x
rhel9

[leapp]
rhel8x
----

Pull in any of our required roles from Ansible Galaxy

[source,bash]
----
cd ansible

ansible-galaxy  install -r requirements.yaml
----

Make sure our RHEL Hosts

* hosts have appropriate hostnames
* are subscribed to RHSM
* have insights enabled
* that leapp is installed on the RHEL8 host
* cockpit is enabled with correct firewall access on our RHEL9 host

[source,bash]
----
ansible-playbook  -i hosts.demo setup-hostname.yaml 
ansible-playbook  -i hosts.demo rhsm_subscribe.yaml
ansible-playbook  -i hosts.demo setup-insights.yaml
ansible-playbook  -i hosts.demo setup-leapp.yaml
ansible-playbook  -i hosts.demo setup-cockpit.yaml
----

Confirm VMs are present in the https://console.redhat.com/insights/inventory[Insights Cloud Console], 
and confirm you're filtering on *_Data Collector : insights-client_*

Now perform a preupgrade run of leapp via SSH as our existing ansible playbook doesn't support RHEL8 -> 9
at this stage


[source,bash]
----
ssh root@rhel8x

dnf check-update

dnf install -y leapp-upgrade cockpit-leapp
systemctl enable --now cockpit.socket
leapp preupgrade --target 9.0
----

== Image Builder Pre-work

We need to define an initial demo tempate we can re-use during the demo.

* Create a base image *live-demo-example* with packages httpd and postgresql
** Target VM and AWS
** Provide your AWS ID.

== Sign into cloud services

Pre-login to to your two cockpit session on *rhel8* and *rhel9* in addition to

* https://console.redhat.com/insights/inventory/?status=fresh&status=stale&source=insights&page=1&per_page=50[Insights Cloud Console]
* https://aws.amazon.com/[AWS Console] for cloud deployment

== Demo Walkthru

=== Webconsole / Cockpit

Show off the cockpit console on our RHEL 8 host

* Overview
* SSH access
* upgrade report

Switch to our RHEL9 hosts and use that to jump into *Insights*

Or alternatively connect to the https://console.redhat.com/insights/inventory/?status=fresh&status=stale&source=insights&page=1&per_page=50[Insights Cloud Console]

=== Insights / Inventory

* RHEL9 host
** Overview -> Advisor - We don't recommend OpenSSH as root anymore
** Vulnerabilty tab - already resolving new vulnerabilities for RHEL9
*** Click on a recent CVE
* [Optional] RHEL8X host 
** Overview -> Vulnerabilities.

=== Image Builder & Launch to Cloud

* Re-create image *live-demo-example* so we can add additional packages etc.
** Show we can add additional targets
** Try to avoid showing our AWS Id
** Add an additional package - eg tmux
** Click Create
* Click on *launch instance* for an existing built image
** Show we can leverage the instance easliy  via the AWS console
** Speak to adding to our AWS environment so we can use in multiple regions



== Environment Cleanup

I recommend you remove your RHSM and Insights entitlements before deleting any virtual machines

[source,bash]
----
# Clean up all hosts in our inventory
ansible-playbook  -i hosts.demo rhsm_unsubscribe.yaml

# Or for one specific host specify the hostname
ansible-playbook  -i hosts.demo rhsm_unsubscribe.yaml -l rhel8x
----

Now remove the virtual machines along with the QCOW2 working snapshots

[source,bash]
----
sudo VM_NAME=RHEL8x ./deploy_vm.sh cleanup

sudo VM_NAME=RHEL9 ./deploy_vm.sh cleanup
----
